server:
  port: 5555

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
#    cache-services:
#      path: /cache-services/**
#      serviceId: cache-services
    message-services:
      path: /message-services/**
      serviceId: message-services
    user-services:
      path: /user-services/**
      serviceId: user-services
    order-services:
      path: /order-services/**
      serviceId: order-services
    crm-services:
      path: /crm-services/**
      serviceId: crm-services

# TODO 用命令行启动时配置
jwtUtil:
  SIGNING_KEY: jskglwejthmndggs8963nko