server:
  port: 5555

spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    redis-services:
      path: /redis-services/**
      serviceId: redis-services
    user-services:
      path: /user-services/**
      serviceId: user-services
