server:
  port: 5555

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    socket-timeout-millis: 4000
    connect-timeout-millis: 6000
  routes:
    user-services:
      path: /user-services/**
      serviceId: user-services

    cache-services:
      path: /cache-services/**
      url: http://localhost
    message-services:
      path: /message-services/**
      url: http://localhost
    order-services:
      path: /order-services/**
      url: http://localhost
    crm-services:
      path: /crm-services/**
      url: http://localhost
    #需要忽略的头部信息，不在传播到其他服务
    sensitive-headers: Access-Control-Allow-Origin
    ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
    #系统url
    ignored-patterns: /**/system/**
#    SimpleHostRoutingFilter:
#            pre:
#                disable: true
# TODO 用命令行启动时配置
jwtUtil:
  SIGNING_KEY: jskglwejthmndggs8963nko


#  #默认1000
#  zuul.host.socket-timeout-millis=2000
#  #默认2000
#  zuul.host.connect-timeout-millis=4000